
project_id = "mjhbugzaqmtfnbxaqpss"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
uri = "http://localhost:54321/auth/v1"

[storage]
enabled = true
port = 54325

[functions]
enabled = true
port = 54326

[functions.process-queue]
verify_jwt = false
