
project_id = "collabspace"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
  [functions.generate-zip]
  verify_jwt = true
  
  [functions.upload-to-ftp]
  verify_jwt = true
  
  [functions.check-download-url]
  verify_jwt = true
  
  [functions.send-album-invitation]
  verify_jwt = true
  
  [functions.analyze-image-ai]
  verify_jwt = true
  
  [functions.analyze-image]
  verify_jwt = true
  
  [functions.cache-dropbox-images]
  verify_jwt = true
  
  [functions.cron-cache-dropbox]
  verify_jwt = true
